version: "2"
services:

  opa_java_test:
    build: docker
    image: opa_java_test
    environment:
      LD_LIBRARY_PATH: /go/src/github.com/llofberg/opa-jnr/
    command: /go/src/github.com/llofberg/opa-jnr/docker/build.sh
    volumes:
      - $GOROOT:/go
